version: '3'

services:
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
  website:
    build: ./djangocrawler
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangocrawler:/app/djangocrawler
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"

volumes:
  redis:

